---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes
    daemon_reload: yes

- name: reload php-fpm
  systemd:
    name: php-fpm
    state: reloaded
    enabled: yes
    daemon_reload: yes
