---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pods-viewer
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: pods-viewer
    namespace: default
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - 'get'
        - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: pods-viewer
subjects:
    - kind: ServiceAccount
      name: pods-viewer
      namespace: default
roleRef:
    kind: ClusterRole
    name: pods-viewer
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: get-pods
  labels:
    app: get-pods
spec:
  serviceAccountName: pods-viewer
  containers:
    - name: get-pods
      image: get_pods:1.3
      ports:
        - name: metrics
          containerPort: 9100
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: get-pods
  labels:
    app: get-pods
spec:
  type: ClusterIP
  ports:
    - port: 9100
  selector:
    app: get-pods