---
- name: Check site's availability
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: healthcheck
      healthcheck_sh:
        addr: "ansible-node1.localdomai"
        tls: true