---
- name: Check site's availability
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: healthcheck
      healthcheck_sh:
        addr: "ansible-node1.localdomai"
        tls: true
      register: bash_result

    - name: print result
      debug:
        msg: "{{ bash_result }}"

#    - name: healthcheck
#      healthcheck_py:
#        addr: "ansible-node1.localdomain"
#        tls: true