---
- name: install pyOpenSSL
  yum:
    name: https://cbs.centos.org/kojifiles/packages/pyOpenSSL/0.15.1/1.el7/noarch/pyOpenSSL-0.15.1-1.el7.noarch.rpm
    state: present
    validate_certs: no

- name: —Åreate SSL directory
  ansible.builtin.file:
    path: "{{ SSL_dir }}"
    state: directory
    owner: root
    group: root   
    mode: '0600'

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ SSL_dir }}/{{ server_hostname }}.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    backup: yes

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ SSL_dir }}/{{ server_hostname }}.csr"
    privatekey_path: "{{ SSL_dir }}/{{ server_hostname }}.key"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    provider: selfsigned
    path: "{{ SSL_dir }}/{{ server_hostname }}.crt"
    privatekey_path: "{{ SSL_dir }}/{{ server_hostname }}.key"
    csr_path: "{{ SSL_dir }}/{{ server_hostname }}.csr"