---
- name: Check site's availability
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: healthcheck_py block
      tags: "sh"
      block:
      - name: healthcheck
        healthcheck_sh:
          addr: "{{ url | default('ansible-node1.localdomain') }}"
          tls: true
        register: bash_result
      - name: print 
        debug:
          msg: "{{ bash_result }}"

    - name: healthcheck_py block
      tags: "py"
      block:
      - name: Install requests python package
        pip:
          name: requests
      - name: healthcheck
        tags: "pyt"
        healthcheck_py:
          addr: "{{ url | default('ansible-node1.localdomain') }}"
          tls: true
        register: py_result
      - name: print result
        debug:
          msg: "{{ py_result }}"